# Generated by Django 4.1 on 2022-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=80, verbose_name='Nome')),
                ('idade', models.IntegerField()),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
