# Generated by Django 4.1 on 2022-08-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='telefone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
